### ISSUE TITLE
Request: License your code

### ISSUE THREAD

**Issue by gorhill** [foo123/RegexAnalyzer#1]
Hello,

I am interested in evaluating whether I can use your RegexAnalyzer code into one of my GPLv3 projects, however there is no license attached to your project, and as a result I can't use your code, which I think would solve the issue I am trying to solve on my side.

So this is a request to pick and assign a license to your code here, such that I will know whether it is compatible with GPLv3 and whether I can use it as a result.

Thanks.

**Comment by foo123** [comment]
The (implied) license is as free as it can get. You can modify it and use it anywhere you want if it suits you.
An attribution to original author would be appreciated but even this is not mandatory.
Copy Left
