### ISSUE TITLE
Flag `s` and `d` not supported for JavaScript

### ISSUE THREAD

**Issue by danny0838** [foo123/RegexAnalyzer#8]
Code: `Regex.Analyzer(/\x0333/dgismuy).compile()`

Actual: `/\x0333/gimuy`

Expected `/\x0333/dgismuy`

Ref: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions#advanced_searching_with_flags

**Comment by foo123** [comment]
new upload of 1.2.0

added new flags
