### ISSUE TITLE
Prevent error for an incomplete sequence for JavaScript

### ISSUE THREAD

**Issue by danny0838** [foo123/RegexAnalyzer#9]
Incomplete sequence should match a literal string rather than throw an error. For example, `\x3` should be treated as `x3`, `/\u00/` be treated as `u00`, `/{/` be treated as matching literal `{`, `/{0,/` be treated as matching literal `{0,`, etc.

**Comment by danny0838** [comment]
A backreference-like sequence is more complicated.

If subgroup `6` doesn't exist, `\6` will be treated as a literal char whose code is octal `6`.

An octal char can range from `\0` to `\377`, a shorter value will be used if the full match exceeds it, e.g. `\477` be treated as `\47` and `7`.

If no valid octal code can be matched, e.g. `\9` will be treated as literal `9`.

**Comment by foo123** [comment]
new upload of 1.2.0

```
/\u00/
{
  "type": 1,
  "val": [
    {
      "type": 1024,
      "val": "u00",
      "flags": {},
      "typeName": "String"
    }
  ],
  "flags": {},
  "typeName": "Sequence"
}
/\x3/
{
  "type": 1,
  "val": [
    {
      "type": 1024,
      "val": "x3",
      "flags": {},
      "typeName": "String"
    }
  ],
  "flags": {},
  "typeName": "Sequence"
}
```

> Incomplete sequence should match a literal string rather than throw an error. For example, \x3 should be treated as x3, /\u00/ be treated as u00,

Done


> /{/ be treated as matching literal {, /{0,/ be treated as matching literal {0,, etc.

Special regex chars MUST be escaped. Not going to add this feature.


> A backreference-like sequence is more complicated.
> 
> If subgroup 6 doesn't exist, \6 will be treated as a literal char whose code is octal 6.
> 
> An octal char can range from \0 to \377, a shorter value will be used if the full match exceeds it, e.g. \477 be treated as \47 and 7.
> 
> If no valid octal code can be matched, e.g. \9 will be treated as literal 9.

Only in a major update, not anytime soon.

**Comment by danny0838** [comment]
> > /{/ be treated as matching literal {, /{0,/ be treated as matching literal {0,, etc.
> 
> Special regex chars MUST be escaped. Not going to add this feature.

I'd like to agree with you. Unfortunately it's the documented browser behavior (See [doc](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions#using_unicode_regular_expressions).)
